android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
# Use in-process strategy to avoid spawning a separate JVM for Kotlin
# kotlin.compiler.execution.strategy=in-process
org.gradle.vfs.watch=false
